return {
	corboucher1 = {
		bmcode = 0,
		buildangle = 8192,
		buildcostenergy = 68725,
		buildcostmetal = 11123,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 4,
		buildinggrounddecalsizey = 4,
		buildinggrounddecaltype = "corboucher_aoplane.dds",
		buildpic = "corboucher.png",
		buildtime = 131000,
		canattack = true,
		canstop = 1,
		category = "ALL NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Small-Anti Experimental Cannon",
		designation = "BOUCHER-GUARD",
		energystorage = 0,
		energyuse = 0,
		explodeas = "MEDIUM_BUILDINGEX",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 7,
		idletime = 1800,
		losemitheight = 71.55766,
		mass = 20740,
		maxdamage = 30000,
		maxslope = 10,
		maxwaterdepth = 0,
		metalstorage = 0,
		name = "Small Bucher",
		noautofire = false,
		nochasecategory = "ALL",
		objectname = "corboucher1",
		radardistance = 0,
		radaremitheight = 71.55766,
		selfdestructas = "MEDIUM_BUILDING",
		shootme = 1,
		side = "CORE",
		sightdistance = 1050,
		standingfireorder = 2,
		script = "corboucher.cob",
		unitname = "corboucher1",
		unitnumber = 731989,
		usebuildinggrounddecal = true,
		workertime = 0,
		yardmap = "ooo ooo ooo",

		featuredefs = {
			dead = {
				blocking = true,
				category = "core_corpses",
				damage = 28000,
				description = "Small Boucher Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 8592,
				object = "corboucher1_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 18800.00195,
				description = "Small Boucher Heap",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 6273.59961,
				object = "3x3d",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twrturn3",
			},
			select = {
				[1] = "twrturn3",
			},
		},
		weapondefs = {
			core_boucher = {
				areaofeffect = 30,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				duration = 0.025,
				energypershot = 25000,
				firestarter = 90,
				id = 254,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.75,
				name = "Cartouche Aluminium",
				noselfdamage = true,
				range = 1400,
				reloadtime = 5,
				rgbcolor = "0.9 0.6 1",
				soundhitdry = "xplolrg1",
				soundstart = "Energy",
				thickness = 5,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 500,
				damage = {
					commanders = 1400,
					default = 7500,
					experimental_land = 15000,
					experimental_ships = 15000,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "LARGE MEDIUM SMALL TINY",
				def = "CORE_BOUCHER",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
