return {
	nebraska2 = {
		bmcode = 0,
		buildangle = 8192,
		buildcostenergy = 422707,
		buildcostmetal = 40042,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 7,
		buildinggrounddecalsizey = 7,
		buildinggrounddecaltype = "nebraska_aoplane.dds",
		buildpic = "nebraska.png",
		buildtime = 508864,
		canattack = true,
		canstop = 1,
		category = "ALL NOTHOVERNOTVTOL NOTMOBILE NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Super-Anti Experimental Cannon",
		designation = "NEBRASKA-HLT",
		energystorage = 0,
		energyuse = 0,
		explodeas = "MEDIUM_BUILDINGEX",
		firestandorders = 1,
		footprintx = 6,
		footprintz = 6,
		icontype = "building",
		idleautoheal = 7,
		idletime = 1800,
		losemitheight = 66.96581,
		mass = 18789,
		maxdamage = 165000,
		maxslope = 10,
		maxwaterdepth = 0,
		metalstorage = 0,
		name = "Super NEBRASKA",
		noautofire = false,
		nochasecategory = "ALL",
		objectname = "NEBRASKA2",
		ovradjust = 1,
		radardistance = 0,
		radaremitheight = 66.96581,
		selfdestructas = "MEDIUM_BUILDING",
		shootme = 1,
		side = "CORE",
		sightdistance = 2550,
		standingfireorder = 2,
		script = "nebraska.cob",
		unitname = "nebraska2",
		unitnumber = 567167,
		usebuildinggrounddecal = true,
		workertime = 0,
		yardmap = "ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo",

		featuredefs = {
			dead = {
				blocking = true,
				category = "core_corpses",
				damage = 80000,
				description = "Super Nebraska Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 6,
				footprintz = 6,
				height = 20,
				hitdensity = 100,
				metal = 25031.2002,
				object = "NEBRASKA2_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 43400,
				description = "Super Nebraska Heap",
				featurereclamate = "smudge01",
				footprintx = 4,
				footprintz = 4,
				height = 4,
				hitdensity = 100,
				metal = 18024.95996,
				object = "4x4d",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servlrg3",
			},
			select = {
				[1] = "servlrg3",
			},
		},
		weapondefs = {
			nebraska_weapon = {
				areaofeffect = 30,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				duration = 0.025,
				energypershot = 150000,
				firestarter = 90,
				id = 254,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.75,
				name = "Annihilator Weapon Nebraska",
				noselfdamage = true,
				range = 3875,
				reloadtime = 5,
				rgbcolor = "0.9 0.6 1",
				soundhitdry = "xplolrg1",
				soundstart = "Energy",
				thickness = 5,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 2000,
				damage = {
					commanders = 10000,
					default = 50000,
					experimental_land = 150000,
					experimental_ships = 150000,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "LARGE MEDIUM SMALL TINY",
				def = "NEBRASKA_WEAPON",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
